# Generated by Django 3.1.5 on 2021-02-08 15:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import dreamhome.utils
import jsonfield.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.SmallIntegerField(choices=[(0, 'Pump'), (1, 'Light'), (2, 'Fan'), (3, 'Air Conditioner'), (4, 'Refrigerator'), (5, 'Cooking Apparatus'), (6, 'TV')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=False)),
                ('manual', models.BooleanField(default=False)),
                ('power_rating', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('voltage_rating', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('active_dur', models.IntegerField(default=0.0)),
                ('total_active_dur', models.IntegerField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'appliances',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cur_voltage_level', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True), size=None)),
                ('cur_current_level', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True), size=None)),
                ('active_duration_min', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(blank=True, null=True), size=None)),
                ('daily_consumption', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True), size=None)),
                ('weekly_consumption', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True), size=None)),
                ('monthly_consumption', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True), size=None)),
                ('yearly_consumption', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True), size=None)),
                ('daily_expanse', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True), size=None)),
                ('weekly_expanse', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True), size=None)),
                ('monthly_expanse', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True), size=None)),
                ('yearly_expanse', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True), size=None)),
                ('total_daily_expanse', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True), size=None)),
                ('total_weekly_expanse', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True), size=None)),
                ('total_monthly_expanse', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True), size=None)),
                ('total_yearly_expanse', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True), size=None)),
            ],
            options={
                'db_table': 'consumption',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15, unique=True)),
                ('mac', models.CharField(max_length=17, validators=[dreamhome.utils.validate_mac])),
                ('key', models.CharField(max_length=40)),
                ('ssid', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('wifi_ssid', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32, null=True), null=True, size=None)),
                ('wifi_pass', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8, null=True), null=True, size=None)),
                ('sim_pin', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='IN')),
                ('ident', models.GenericIPAddressField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_online', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'device',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'home',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.SmallIntegerField(choices=[(0, 'Water Tank'), (1, 'Room Lumminous'), (2, 'Room Temperator')], default=0)),
                ('sensor_val', models.FloatField(default=0.0)),
                ('sensor_max_val', models.FloatField(default=1023)),
                ('sensor_min_val', models.FloatField(default=0.0)),
                ('dimensions_data', jsonfield.fields.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'operator',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PortInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17, validators=[dreamhome.utils.validate_mac])),
                ('port', models.CharField(max_length=2)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'port_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.SmallIntegerField(choices=[(0, 'Pump Room'), (1, 'Bed Room'), (2, 'Kitchen Room'), (3, 'Drawing Room'), (4, 'Dining Room'), (5, 'Guest Room'), (6, 'Wash Room')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliances.home')),
            ],
            options={
                'db_table': 'room',
                'managed': True,
            },
        ),
    ]
