# Generated by Django 3.1.5 on 2021-02-08 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appliances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portinfo',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliances.device'),
        ),
        migrations.AddField(
            model_name='portinfo',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appliances.home'),
        ),
        migrations.AddField(
            model_name='portinfo',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appliances.room'),
        ),
        migrations.AddField(
            model_name='portinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operator',
            name='appliances',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliances.appliances'),
        ),
        migrations.AddField(
            model_name='operator',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliances.device'),
        ),
        migrations.AddField(
            model_name='operator',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliances.home'),
        ),
        migrations.AddField(
            model_name='operator',
            name='port',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appliances.portinfo'),
        ),
        migrations.AddField(
            model_name='operator',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliances.room'),
        ),
        migrations.AddField(
            model_name='operator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='home',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appliances.home'),
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumption',
            name='appliances',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliances.appliances'),
        ),
        migrations.AddField(
            model_name='consumption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appliances',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliances.device'),
        ),
        migrations.AddField(
            model_name='appliances',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliances.home'),
        ),
        migrations.AddField(
            model_name='appliances',
            name='port',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appliances.portinfo'),
        ),
        migrations.AddField(
            model_name='appliances',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliances.room'),
        ),
        migrations.AddField(
            model_name='appliances',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='portinfo',
            unique_together={('device', 'mac', 'port')},
        ),
    ]
