# Generated by Django 3.1.5 on 2021-02-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0002_auto_20210208_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='calibration_ref1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operator',
            name='calibration_ref2',
            field=models.BooleanField(default=False),
        ),
    ]
