"""
Django settings for dreamhome project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""


import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/


DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',       
    'rest_framework',
    'rest_framework.authtoken', 
    'phonenumbers',      
    'phonenumber_field',
    'auth_app',
    'appliances',
]


MIDDLEWARE = [
    'dreamhome.middleware.CustomMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'dreamhome.urls'

SSL = False

SESSION_EXPIRE_AT_BROWSER_CLOSE =   False

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'template/templates', ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
            'libraries' : {
                'dh_static' : 'dreamhome.template.templatetags',
                'date_formater' : 'dreamhome.template.templatetags',
            }
        },
    },
]

STATICFILES_DIRS = [ 
                        BASE_DIR / 'static',
                    ]
STATIC_ROOT = 'static'


STATICFILES_FINDERS = (
                        'django.contrib.staticfiles.finders.FileSystemFinder',
                        'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)


WSGI_APPLICATION = 'dreamhome.wsgi.application'
# ASGI_APPLICATION = 'dreamhome.asgi.application'


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "auth_app.AuthUser"

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

# PHONENUMBER_DB_FORMAT = 'NATIONAL'
PHONENUMBER_DEFAULT_REGION  =   'IN'

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'


DATABASES = {
    'local': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': f'{BASE_DIR}/../db.sqlite3',
    }
}

DATABASE_ROUTERS = ['dreamhome.db_router.DbRouter']

MAC_IMEI_AUTHENTICATION_BACKENDS = ['auth_app.backends.MACIMEIBackend']


CACHE_TTL = 24*60*60
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': BASE_DIR / 'caches',
    },
    "celery": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379",
        "OPTIONS": {
            "DB": 'nc-celery',
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    'throttling': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/',
        'OPTIONS': {
            "DB": 'nc-throttling',
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    },
}

BROKER_URL = CACHES['celery']['LOCATION']  #'redis://127.0.0.1:6379' #values.Value('redis://localhost:6379/0')
BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 3600,
    'fanout_prefix': True,
    'fanout_patterns': True,
}
BROKER_CONNECTION_RETRY = True
BROKER_CONNECTION_MAX_RETRIES = 0

CELERY_TASK_SERIALIZER      =   'json' #'pickle'
CELERY_RESULT_SERIALIZER    =   'json' #'pickle'
CELERY_RESULT_BACKEND       =   CACHES['celery']['LOCATION'] #'redis://127.0.0.1:6379'  #values.Value('redis')
CELERY_TASK_RESULT_EXPIRES  =   3600
CELERY_ACCEPT_CONTENT       =   ['pickle', 'application/json', 'msgpack', 'yaml']
CELERY_DISABLE_RATE_LIMITS  =   True
CELERY_CHORD_PROPAGATES     =   True
# CELERY_ALWAYS_EAGER = False
# CELERY_DEFAULT_QUEUE = values.Value('celery', environ_name='QUEUE_NAME')
CELERY_TIMEZONE             =   'Asia/Kolkata'
USE_TZ                      =   False



USER_TYPE   =   (
                    "dreamhome",
                    "device",
                    "home",
                )

USER_GROUP  =   (
                    "admin",
                    "staff",
                    "client",
                )

ROOM_CATEGORY       = (
                        "Pump Room",
                        "Bed Room",
                        "Kitchen Room",
                        "Drawing Room",
                        "Dining Room",
                        "Guest Room",
                        "Wash Room",
    )

APPLIANCES_CATEGORY   = (
                            "Pump",# With Control Pannel",
                            "Pump With Single Switch",
                            "Light",
                            "Fan",
                            "Air Conditioner",
                            "Refrigerator",
                            "Cooking Apparatus",
                            "TV",
    )

OPERATOR_CATEGORY   =   (

                            "Water Tank",
                            "Room Lumminous",
                            "Room Temperator",

    )

APPLIANCES_OPERATOR_MAPPING   = (
    (APPLIANCES_CATEGORY[0], (OPERATOR_CATEGORY[0],)),
    (APPLIANCES_CATEGORY[1], (OPERATOR_CATEGORY[1],)),
    (APPLIANCES_CATEGORY[2], (OPERATOR_CATEGORY[2],)),
    (APPLIANCES_CATEGORY[3], (OPERATOR_CATEGORY[2],)),
    (APPLIANCES_CATEGORY[4], ()),
    (APPLIANCES_CATEGORY[5], ()),
    (APPLIANCES_CATEGORY[6], ()),
)


SAFE_STATUS_CODE = [200, 201]


DEFAULT_THROTTLE_RATES = {
    'anonymous'     :   [ 10, 10, 10, 15*60, 15], # 15 request per 10 secs
    'auth_user'     :   [ 100, 10 ], # 50 request per 10 secs
    'requests'      :   [ 100, 10 ], # 30 request per 10 secs
}


REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        ],
     'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'auth_app.throttling.DeviceRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon'      :   '20/minute',
        'user'      :   '20/minute',
        'device'    :   '20/minute',
        'post_anon' :   '20/minute',
        'get_anon'  :   '100/minute',
        'post_user' :   '80/minute',
        'get_user'  :   '150/minute',
        'post_device' :   '30/minute',
        'get_device'  :   '60/minute'        
    }
}


RELAY_POWER_RATING    = 2500
RELAY_VOLTAGE_RATING  = 250


if DEBUG:
    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)



